GET http://localhost:8000/auth/users/me/ HTTP/1.1



### 
POST http://localhost:8000/auth/token/login/  HTTP/1.1
Content-Type: application/json

{
   "username": "admin",
   "password": "test" 
}



### 
POST http://localhost:8000/auth/token/logout/  HTTP/1.1
Authorization: Token 336d3c437ae99c563fa4d6c08abb1c43bbfd7249





#######################  JWT
GET http://localhost:8000/auth/users/me/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzUxMDQ5LCJpYXQiOjE3NTE3NTA3NDksImp0aSI6IjBiYjhiMDg0NTE3YzRjNmZiZGU4MjMwNzdlNDA1YzNhIiwidXNlcl9pZCI6MX0.JXJFwIqOqP7JUlb-WywLwEmoIVEO7E3A-Ft8g72YQew




### JWT 로그인
POST http://localhost:8000/auth/jwt/create/  HTTP/1.1
Content-Type: application/json

{
   "username": "admin",
   "password": "test" 
}



### verify 유효성 체크
POST http://localhost:8000/auth/jwt/verify/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzUxMzk2LCJpYXQiOjE3NTE3NTEwOTYsImp0aSI6IjY4YTRmMWJiNmFjMDRkMmZhMmE2OGQ3ZjEyZTJlMGQ5IiwidXNlcl9pZCI6MX0.KV71Rm-RkQF-e6g745samZEdomVkvuHuo79J2pmjgwo

{
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzUxMzk2LCJpYXQiOjE3NTE3NTEwOTYsImp0aSI6IjY4YTRmMWJiNmFjMDRkMmZhMmE2OGQ3ZjEyZTJlMGQ5IiwidXNlcl9pZCI6MX0.KV71Rm-RkQF-e6g745samZEdomVkvuHuo79J2pmjgwo"
}




###  JWT   토큰 갱신
POST http://localhost:8000/auth/jwt/refresh/  HTTP/1.1
Content-Type: application/json

{
   "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MTgzNzU5MCwiaWF0IjoxNzUxNzUxMTkwLCJqdGkiOiI3ODg1MTYxNjY1MDU0MDZjOWU3ODQ3NWE4N2RiN2RkNCIsInVzZXJfaWQiOjF9.WAdtssbMN1xnNQ_P9kxlYI00HhGVejLa1HqNcvdu1kY"
}